# This is a basic workflow to help you get started with Actions

name: Scrape arrests and activity

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: grab python dependencies
        run: python -m pip install requests beautifulsoup4 datetime pandas
      
      # Runs a single command using the runners shell
      - name: Run activity scraper
        run: python activity_scraper.py

      # Runs a set of commands using the runners shell
      - name: Run arrest scraper
        run: python arrest_scraper.py

      - name: Commit and push if it changed
        run: |-
          git config user.name "scraper-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest arrest and activity data: ${timestamp}" || exit 0
          git push
